orqueio:
  bpm:
    oauth2:
      identity-provider:
        enabled: true
        group-name-attribute: groups
      user-sync:
        enabled: true
        sync-groups: true
#        remove-obsolete-group-memberships: true
    authorization:
      enabled: true
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks
    run:
      auth.enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: YOUR_KEYCLOAK_CLIENT_ID
            client-secret: YOUR_KEYCLOAK_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - read:user
              - user:email
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          auth0:
            client-id: YOUR_AUTH0_CLIENT_ID
            client-secret: YOUR_AUTH0_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          okta:
            client-id: YOUR_OKTA_CLIENT_ID
            client-secret: YOUR_OKTA_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/orqueio
            user-name-attribute: preferred_username

          google:
            issuer-uri: https://accounts.google.com
            user-name-attribute: email

          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

          auth0:
            issuer-uri: YOUR_AUTH0_ISSUER_URI
            user-name-attribute: email

          okta:
            issuer-uri: YOUR_OKTA_ISSUER_URI
            user-name-attribute: email

server:
  port: 8080